# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [80]:
import numpy as np

In [81]:
np.random.randint(0, 20, size = (4, 7))

array([[12, 15, 13, 10, 13,  0,  0],
       [16,  9,  2,  1,  7, 16,  5],
       [ 2, 13, 11,  3,  7, 15, 11],
       [16, 11, 13, 18, 18,  4,  4]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [82]:
np.random.randint(0, 10, size = (8, 10))

array([[8, 7, 8, 7, 6, 7, 2, 9, 8, 0],
       [0, 4, 2, 4, 1, 0, 1, 5, 0, 6],
       [8, 5, 0, 7, 9, 6, 5, 3, 0, 7],
       [4, 8, 6, 4, 8, 8, 8, 0, 7, 9],
       [8, 3, 3, 9, 4, 9, 7, 7, 8, 1],
       [6, 6, 1, 2, 7, 5, 5, 8, 5, 8],
       [5, 8, 8, 9, 7, 3, 0, 1, 4, 5],
       [4, 8, 4, 9, 6, 4, 5, 6, 0, 4]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [83]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [2]:
import numpy as np
ar1 = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', skiprows=1, dtype=np.int32)
strings = ar1[:5,:]
strings

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [3]:
import numpy as np
ar2 = ar1[:,1:]
print(f'Среднее значение:{ar2.mean(axis=0)}, минимум:{ar2.min(axis=0)}, максимум:{ar2.max(axis=0)}, медиана:{np.median(ar2, axis=0)}')

Среднее значение:[2.16010017e+04 9.05528000e+00], минимум:[0 1], максимум:[2147483647         39], медиана:[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [38]:
qv = np.quantile(ar1[:,1], q=0.75, axis=0)
ar1[ar1[:, 1] <= qv]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [ 43407,     35,      7],
       [498432,     65,     15],
       [370915,      5,      4]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [103]:
print(len(ar1[:, 1]) - np.count_nonzero(ar1[:, 1]))

479


In [104]:
ar1[ar1[:, 1] == 0] = 1
print(len(ar1[:, 1]) - np.count_nonzero(ar1[:, 1]))

0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [109]:
ar3 = np.unique(ar1, axis = 1)
print(len(ar3))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [112]:
print(len(np.unique(ar1[:,2])))
np.unique(ar1[:,2])

37


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 37, 39])

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [127]:
ar3 = ar1[ar1[:, 2] <= 5]
print(ar3)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [8]:
value = ar1[:, 2] / ari[:, 1]
print(value.max(axis=0))

23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [37]:
ar_sorted = ar1[ar1[:, 1].argsort()]
ar_sorted = ar_sorted[-100:]
np.mean(ar_sorted[:, 2])

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [11]:
n = 10
index = np.random.choice(ar1.shape[0], n, replace=False)
ar1[index]

array([[ 50787,     30,      6],
       [270618,     60,     10],
       [129357,      5,      5],
       [168184,      7,      3],
       [121897,     15,      6],
       [168475,     30,     14],
       [255210,     45,      8],
       [153700,      7,      5],
       [ 36559,     10,      4],
       [421962,     15,      9]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [135]:
print(f'{len(ar1[ar1[:, 2] < ar1[:,2].mean(axis=0)]) / len(ar1) * 100}%')

58.989000000000004%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [85]:
column_to_be_added = np.array([[0]] * len(ar1))
arr_almost = np.append(ar1, column_to_be_added, axis=1)
arr_almost[:,3] = np.where((ar1[:,1] <= 20) & (ar1[:,2] <=5), 1, 0)
print(arr_almost)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [51]:
true_ = ar1[(ar1[:,1] <= 20) & (ar1[:,2] <=5)]
print(f'{len(true_) / len(ar1) *100}%')

9.552%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.